# Сообщаем CMake, что это toolchain файл
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

# Toolchain file для Clang.
SET(TOOLCHAIN_DIRECTORY /usr/bin)

# Компиляторы
SET(CMAKE_C_COMPILER ${TOOLCHAIN_DIRECTORY}/clang)
SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIRECTORY}/clang++)
SET(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})

# Утилиты
SET(CMAKE_OBJCOPY ${TOOLCHAIN_DIRECTORY}/llvm-objcopy)
SET(CMAKE_OBJDUMP ${TOOLCHAIN_DIRECTORY}/llvm-objdump)
SET(CMAKE_SIZE ${TOOLCHAIN_DIRECTORY}/llvm-size)

# Стандарт C++
SET(CMAKE_CXX_STANDARD 23)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_CXX_EXTENSIONS OFF)
